version: "3"
services:

  # Postgres service
  db:
    image: postgres:12
    container_name: db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - google-crawler

  # PHP Service
  lumen:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini # mapping php.ini
      #      - ./docker/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf # mapping supervisord.conf
      - ./log:/var/log/nginx
      - ./:/var/www/html
    command: >
      bash -c "cd /var/www/html && composer install --prefer-dist && cp .env.example .env &&
              php artisan migrate &&
              /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT}
    networks:
      - google-crawler

volumes:
  db_data:

networks:
  google-crawler:
    driver: bridge
